bind 127.0.0.1
port 6379
timeout 0
tcp-keepalive 300

daemonize yes
supervised systemd
pidfile /run/redis/redis-business.pid
loglevel notice
logfile /var/log/redis/redis-business.log
dir /var/lib/redis

save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly-business.aof"

maxmemory 512mb
maxmemory-policy allkeys-lru
